/*****************************************************************************
 * Project: RooFit                                                           *
 *                                                                           *
 * This code was autogenerated by RooClassFactory                            *
 *                                                                           *
 * Code massaged by Giulio Dujany - University of Manchester                 *
 *****************************************************************************/

#ifndef ROODSCBSHAPEOLD
#define ROODSCBSHAPEOLD

#include "RooAbsPdf.h"
#include "RooRealProxy.h"
#include "RooCategoryProxy.h"
#include "RooAbsReal.h"
#include "RooAbsCategory.h"

class RooDSCBShapeOld : public RooAbsPdf {
public:
  RooDSCBShapeOld() {} ;
  RooDSCBShapeOld(const char *name, const char *title,
	      RooAbsReal& _x,
	      RooAbsReal& _mu,
	      RooAbsReal& _sig,
	      RooAbsReal& _a1,
	      RooAbsReal& _n1,
	      RooAbsReal& _a2,
	      RooAbsReal& _n2);
  RooDSCBShapeOld(const RooDSCBShapeOld& other, const char* name=0) ;
  virtual TObject* clone(const char* newname) const { return new RooDSCBShapeOld(*this,newname); }
  inline virtual ~RooDSCBShapeOld() { }

protected:

  RooRealProxy x ;
  RooRealProxy mu ;
  RooRealProxy sig ;
  RooRealProxy a1 ;
  RooRealProxy n1 ;
  RooRealProxy a2 ;
  RooRealProxy n2 ;

  Double_t evaluate() const ;

private:

  ClassDef(RooDSCBShapeOld,1) // Your description goes here...
};

#endif
